### ISSUE TITLE
Play 2.7 support

### ISSUE THREAD

**Issue by dmitchellmim** [KarelCemus/play-i18n#16]
Do you plan to support Play 2.7 with your plugin? I was upgrading a project from 2.6 and encountered the injection error below. Scala and dependency injection are not my strong points, so I'm struggling to troubleshoot this.

```
ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: play.api.i18n.DefaultMessagesApi$.$lessinit$greater$default$6()Lplay/api/http/HttpConfiguration;
  at play.ext.i18n.MultiFormatMessagesApi.<init>(MultiFormatMessagesModule.scala:16)
  at play.ext.i18n.MultiFormatMessagesApi.class(MultiFormatMessagesModule.scala:16)
  while locating play.ext.i18n.MultiFormatMessagesApi
  while locating play.api.i18n.MessagesApi
    for the 1st parameter of play.i18n.MessagesApi.<init>(MessagesApi.java:30)
  at play.ext.i18n.MultiFormatMessagesModule.bindings(MultiFormatMessagesModule.scala:53):
Binding(class play.i18n.MessagesApi to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$4)
  while locating play.i18n.MessagesApi
[...]
```

Anyone else experiencing this? Thanks in advance.

**Comment by KarelCemus** [comment]
I'll update by the end of this week.
